// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: registry.proto

package registry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentCard     *AgentCard             `protobuf:"bytes,1,opt,name=agent_card,json=agentCard,proto3" json:"agent_card,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetAgentCard() *AgentCard {
	if x != nil {
		return x.AgentCard
	}
	return nil
}

func (x *RegisterAgentRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterAgentRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{1}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type UpdateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentCard     *AgentCard             `protobuf:"bytes,2,opt,name=agent_card,json=agentCard,proto3" json:"agent_card,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateAgentRequest) GetAgentCard() *AgentCard {
	if x != nil {
		return x.AgentCard
	}
	return nil
}

func (x *UpdateAgentRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateAgentRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DeleteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{4}
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Skill         string                 `protobuf:"bytes,4,opt,name=skill,proto3" json:"skill,omitempty"`
	Verified      bool                   `protobuf:"varint,5,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAgentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAgentsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListAgentsRequest) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *ListAgentsRequest) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*RegistryEntry       `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{6}
}

func (x *ListAgentsResponse) GetAgents() []*RegistryEntry {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAgentsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAgentsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatResponse) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

type RegistryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentCard     *AgentCard             `protobuf:"bytes,3,opt,name=agent_card,json=agentCard,proto3" json:"agent_card,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Verified      bool                   `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryEntry) Reset() {
	*x = RegistryEntry{}
	mi := &file_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryEntry) ProtoMessage() {}

func (x *RegistryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryEntry.ProtoReflect.Descriptor instead.
func (*RegistryEntry) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{9}
}

func (x *RegistryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegistryEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegistryEntry) GetAgentCard() *AgentCard {
	if x != nil {
		return x.AgentCard
	}
	return nil
}

func (x *RegistryEntry) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RegistryEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegistryEntry) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *RegistryEntry) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *RegistryEntry) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *RegistryEntry) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *RegistryEntry) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AgentCard struct {
	state                             protoimpl.MessageState     `protogen:"open.v1"`
	Did                               string                     `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Name                              string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description                       string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DocumentationUrl                  string                     `protobuf:"bytes,4,opt,name=documentation_url,json=documentationUrl,proto3" json:"documentation_url,omitempty"`
	IconUrl                           string                     `protobuf:"bytes,5,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Version                           string                     `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion                   string                     `protobuf:"bytes,7,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Provider                          *AgentProvider             `protobuf:"bytes,8,opt,name=provider,proto3" json:"provider,omitempty"`
	SupportedInterfaces               []*AgentInterface          `protobuf:"bytes,9,rep,name=supported_interfaces,json=supportedInterfaces,proto3" json:"supported_interfaces,omitempty"`
	Capabilities                      *AgentCapabilities         `protobuf:"bytes,10,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Skills                            []*AgentSkill              `protobuf:"bytes,11,rep,name=skills,proto3" json:"skills,omitempty"`
	DefaultInputModes                 []string                   `protobuf:"bytes,12,rep,name=default_input_modes,json=defaultInputModes,proto3" json:"default_input_modes,omitempty"`
	DefaultOutputModes                []string                   `protobuf:"bytes,13,rep,name=default_output_modes,json=defaultOutputModes,proto3" json:"default_output_modes,omitempty"`
	Security                          []*Security                `protobuf:"bytes,14,rep,name=security,proto3" json:"security,omitempty"`
	SecuritySchemes                   map[string]*SecurityScheme `protobuf:"bytes,15,rep,name=security_schemes,json=securitySchemes,proto3" json:"security_schemes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Signatures                        []*AgentCardSignature      `protobuf:"bytes,16,rep,name=signatures,proto3" json:"signatures,omitempty"`
	SupportsAuthenticatedExtendedCard bool                       `protobuf:"varint,17,opt,name=supports_authenticated_extended_card,json=supportsAuthenticatedExtendedCard,proto3" json:"supports_authenticated_extended_card,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *AgentCard) Reset() {
	*x = AgentCard{}
	mi := &file_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCard) ProtoMessage() {}

func (x *AgentCard) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCard.ProtoReflect.Descriptor instead.
func (*AgentCard) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{10}
}

func (x *AgentCard) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *AgentCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentCard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentCard) GetDocumentationUrl() string {
	if x != nil {
		return x.DocumentationUrl
	}
	return ""
}

func (x *AgentCard) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *AgentCard) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentCard) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *AgentCard) GetProvider() *AgentProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *AgentCard) GetSupportedInterfaces() []*AgentInterface {
	if x != nil {
		return x.SupportedInterfaces
	}
	return nil
}

func (x *AgentCard) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentCard) GetSkills() []*AgentSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *AgentCard) GetDefaultInputModes() []string {
	if x != nil {
		return x.DefaultInputModes
	}
	return nil
}

func (x *AgentCard) GetDefaultOutputModes() []string {
	if x != nil {
		return x.DefaultOutputModes
	}
	return nil
}

func (x *AgentCard) GetSecurity() []*Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *AgentCard) GetSecuritySchemes() map[string]*SecurityScheme {
	if x != nil {
		return x.SecuritySchemes
	}
	return nil
}

func (x *AgentCard) GetSignatures() []*AgentCardSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *AgentCard) GetSupportsAuthenticatedExtendedCard() bool {
	if x != nil {
		return x.SupportsAuthenticatedExtendedCard
	}
	return false
}

type AgentProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  string                 `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentProvider) Reset() {
	*x = AgentProvider{}
	mi := &file_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProvider) ProtoMessage() {}

func (x *AgentProvider) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProvider.ProtoReflect.Descriptor instead.
func (*AgentProvider) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{11}
}

func (x *AgentProvider) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *AgentProvider) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AgentInterface struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolBinding string                 `protobuf:"bytes,1,opt,name=protocol_binding,json=protocolBinding,proto3" json:"protocol_binding,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentInterface) Reset() {
	*x = AgentInterface{}
	mi := &file_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInterface) ProtoMessage() {}

func (x *AgentInterface) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInterface.ProtoReflect.Descriptor instead.
func (*AgentInterface) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{12}
}

func (x *AgentInterface) GetProtocolBinding() string {
	if x != nil {
		return x.ProtocolBinding
	}
	return ""
}

func (x *AgentInterface) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AgentCapabilities struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Streaming              bool                   `protobuf:"varint,1,opt,name=streaming,proto3" json:"streaming,omitempty"`
	PushNotifications      bool                   `protobuf:"varint,2,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	StateTransitionHistory bool                   `protobuf:"varint,3,opt,name=state_transition_history,json=stateTransitionHistory,proto3" json:"state_transition_history,omitempty"`
	Extensions             []*AgentExtension      `protobuf:"bytes,4,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentCapabilities) Reset() {
	*x = AgentCapabilities{}
	mi := &file_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilities) ProtoMessage() {}

func (x *AgentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilities.ProtoReflect.Descriptor instead.
func (*AgentCapabilities) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{13}
}

func (x *AgentCapabilities) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *AgentCapabilities) GetPushNotifications() bool {
	if x != nil {
		return x.PushNotifications
	}
	return false
}

func (x *AgentCapabilities) GetStateTransitionHistory() bool {
	if x != nil {
		return x.StateTransitionHistory
	}
	return false
}

func (x *AgentCapabilities) GetExtensions() []*AgentExtension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type AgentExtension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExtension) Reset() {
	*x = AgentExtension{}
	mi := &file_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExtension) ProtoMessage() {}

func (x *AgentExtension) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExtension.ProtoReflect.Descriptor instead.
func (*AgentExtension) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{14}
}

func (x *AgentExtension) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *AgentExtension) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentExtension) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AgentExtension) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type AgentSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Examples      []string               `protobuf:"bytes,4,rep,name=examples,proto3" json:"examples,omitempty"`
	InputModes    []string               `protobuf:"bytes,5,rep,name=input_modes,json=inputModes,proto3" json:"input_modes,omitempty"`
	OutputModes   []string               `protobuf:"bytes,6,rep,name=output_modes,json=outputModes,proto3" json:"output_modes,omitempty"`
	Security      []*Security            `protobuf:"bytes,7,rep,name=security,proto3" json:"security,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSkill) Reset() {
	*x = AgentSkill{}
	mi := &file_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSkill) ProtoMessage() {}

func (x *AgentSkill) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSkill.ProtoReflect.Descriptor instead.
func (*AgentSkill) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{15}
}

func (x *AgentSkill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentSkill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentSkill) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

func (x *AgentSkill) GetInputModes() []string {
	if x != nil {
		return x.InputModes
	}
	return nil
}

func (x *AgentSkill) GetOutputModes() []string {
	if x != nil {
		return x.OutputModes
	}
	return nil
}

func (x *AgentSkill) GetSecurity() []*Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *AgentSkill) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Security struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemes       map[string]*StringList `protobuf:"bytes,1,rep,name=schemes,proto3" json:"schemes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{16}
}

func (x *Security) GetSchemes() map[string]*StringList {
	if x != nil {
		return x.Schemes
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{17}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SecurityScheme struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Description string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Scheme:
	//
	//	*SecurityScheme_ApiKey
	//	*SecurityScheme_HttpAuth
	//	*SecurityScheme_Mtls
	//	*SecurityScheme_Oauth2
	//	*SecurityScheme_Oidc
	Scheme        isSecurityScheme_Scheme `protobuf_oneof:"scheme"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityScheme) Reset() {
	*x = SecurityScheme{}
	mi := &file_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityScheme) ProtoMessage() {}

func (x *SecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityScheme.ProtoReflect.Descriptor instead.
func (*SecurityScheme) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{18}
}

func (x *SecurityScheme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecurityScheme) GetScheme() isSecurityScheme_Scheme {
	if x != nil {
		return x.Scheme
	}
	return nil
}

func (x *SecurityScheme) GetApiKey() *APIKeySecurityScheme {
	if x != nil {
		if x, ok := x.Scheme.(*SecurityScheme_ApiKey); ok {
			return x.ApiKey
		}
	}
	return nil
}

func (x *SecurityScheme) GetHttpAuth() *HTTPAuthSecurityScheme {
	if x != nil {
		if x, ok := x.Scheme.(*SecurityScheme_HttpAuth); ok {
			return x.HttpAuth
		}
	}
	return nil
}

func (x *SecurityScheme) GetMtls() *MutualTLSSecurityScheme {
	if x != nil {
		if x, ok := x.Scheme.(*SecurityScheme_Mtls); ok {
			return x.Mtls
		}
	}
	return nil
}

func (x *SecurityScheme) GetOauth2() *OAuth2SecurityScheme {
	if x != nil {
		if x, ok := x.Scheme.(*SecurityScheme_Oauth2); ok {
			return x.Oauth2
		}
	}
	return nil
}

func (x *SecurityScheme) GetOidc() *OpenIDConnectSecurityScheme {
	if x != nil {
		if x, ok := x.Scheme.(*SecurityScheme_Oidc); ok {
			return x.Oidc
		}
	}
	return nil
}

type isSecurityScheme_Scheme interface {
	isSecurityScheme_Scheme()
}

type SecurityScheme_ApiKey struct {
	ApiKey *APIKeySecurityScheme `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3,oneof"`
}

type SecurityScheme_HttpAuth struct {
	HttpAuth *HTTPAuthSecurityScheme `protobuf:"bytes,3,opt,name=http_auth,json=httpAuth,proto3,oneof"`
}

type SecurityScheme_Mtls struct {
	Mtls *MutualTLSSecurityScheme `protobuf:"bytes,4,opt,name=mtls,proto3,oneof"`
}

type SecurityScheme_Oauth2 struct {
	Oauth2 *OAuth2SecurityScheme `protobuf:"bytes,5,opt,name=oauth2,proto3,oneof"`
}

type SecurityScheme_Oidc struct {
	Oidc *OpenIDConnectSecurityScheme `protobuf:"bytes,6,opt,name=oidc,proto3,oneof"`
}

func (*SecurityScheme_ApiKey) isSecurityScheme_Scheme() {}

func (*SecurityScheme_HttpAuth) isSecurityScheme_Scheme() {}

func (*SecurityScheme_Mtls) isSecurityScheme_Scheme() {}

func (*SecurityScheme_Oauth2) isSecurityScheme_Scheme() {}

func (*SecurityScheme_Oidc) isSecurityScheme_Scheme() {}

type APIKeySecurityScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeySecurityScheme) Reset() {
	*x = APIKeySecurityScheme{}
	mi := &file_registry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeySecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeySecurityScheme) ProtoMessage() {}

func (x *APIKeySecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeySecurityScheme.ProtoReflect.Descriptor instead.
func (*APIKeySecurityScheme) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{19}
}

func (x *APIKeySecurityScheme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeySecurityScheme) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *APIKeySecurityScheme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type HTTPAuthSecurityScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	BearerFormat  string                 `protobuf:"bytes,2,opt,name=bearer_format,json=bearerFormat,proto3" json:"bearer_format,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPAuthSecurityScheme) Reset() {
	*x = HTTPAuthSecurityScheme{}
	mi := &file_registry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPAuthSecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPAuthSecurityScheme) ProtoMessage() {}

func (x *HTTPAuthSecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPAuthSecurityScheme.ProtoReflect.Descriptor instead.
func (*HTTPAuthSecurityScheme) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{20}
}

func (x *HTTPAuthSecurityScheme) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *HTTPAuthSecurityScheme) GetBearerFormat() string {
	if x != nil {
		return x.BearerFormat
	}
	return ""
}

func (x *HTTPAuthSecurityScheme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MutualTLSSecurityScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutualTLSSecurityScheme) Reset() {
	*x = MutualTLSSecurityScheme{}
	mi := &file_registry_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutualTLSSecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutualTLSSecurityScheme) ProtoMessage() {}

func (x *MutualTLSSecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutualTLSSecurityScheme.ProtoReflect.Descriptor instead.
func (*MutualTLSSecurityScheme) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{21}
}

func (x *MutualTLSSecurityScheme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type OAuth2SecurityScheme struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Flows             *OAuthFlows            `protobuf:"bytes,1,opt,name=flows,proto3" json:"flows,omitempty"`
	Oauth2MetadataUrl string                 `protobuf:"bytes,2,opt,name=oauth2_metadata_url,json=oauth2MetadataUrl,proto3" json:"oauth2_metadata_url,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OAuth2SecurityScheme) Reset() {
	*x = OAuth2SecurityScheme{}
	mi := &file_registry_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2SecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2SecurityScheme) ProtoMessage() {}

func (x *OAuth2SecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2SecurityScheme.ProtoReflect.Descriptor instead.
func (*OAuth2SecurityScheme) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{22}
}

func (x *OAuth2SecurityScheme) GetFlows() *OAuthFlows {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *OAuth2SecurityScheme) GetOauth2MetadataUrl() string {
	if x != nil {
		return x.Oauth2MetadataUrl
	}
	return ""
}

func (x *OAuth2SecurityScheme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type OAuthFlows struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationCode *OAuthFlow             `protobuf:"bytes,1,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	ClientCredentials *OAuthFlow             `protobuf:"bytes,2,opt,name=client_credentials,json=clientCredentials,proto3" json:"client_credentials,omitempty"`
	Implicit          *OAuthFlow             `protobuf:"bytes,3,opt,name=implicit,proto3" json:"implicit,omitempty"`
	Password          *OAuthFlow             `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OAuthFlows) Reset() {
	*x = OAuthFlows{}
	mi := &file_registry_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthFlows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthFlows) ProtoMessage() {}

func (x *OAuthFlows) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthFlows.ProtoReflect.Descriptor instead.
func (*OAuthFlows) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{23}
}

func (x *OAuthFlows) GetAuthorizationCode() *OAuthFlow {
	if x != nil {
		return x.AuthorizationCode
	}
	return nil
}

func (x *OAuthFlows) GetClientCredentials() *OAuthFlow {
	if x != nil {
		return x.ClientCredentials
	}
	return nil
}

func (x *OAuthFlows) GetImplicit() *OAuthFlow {
	if x != nil {
		return x.Implicit
	}
	return nil
}

func (x *OAuthFlows) GetPassword() *OAuthFlow {
	if x != nil {
		return x.Password
	}
	return nil
}

type OAuthFlow struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationUrl string                 `protobuf:"bytes,1,opt,name=authorization_url,json=authorizationUrl,proto3" json:"authorization_url,omitempty"`
	TokenUrl         string                 `protobuf:"bytes,2,opt,name=token_url,json=tokenUrl,proto3" json:"token_url,omitempty"`
	RefreshUrl       string                 `protobuf:"bytes,3,opt,name=refresh_url,json=refreshUrl,proto3" json:"refresh_url,omitempty"`
	Scopes           map[string]string      `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OAuthFlow) Reset() {
	*x = OAuthFlow{}
	mi := &file_registry_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthFlow) ProtoMessage() {}

func (x *OAuthFlow) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthFlow.ProtoReflect.Descriptor instead.
func (*OAuthFlow) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{24}
}

func (x *OAuthFlow) GetAuthorizationUrl() string {
	if x != nil {
		return x.AuthorizationUrl
	}
	return ""
}

func (x *OAuthFlow) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *OAuthFlow) GetRefreshUrl() string {
	if x != nil {
		return x.RefreshUrl
	}
	return ""
}

func (x *OAuthFlow) GetScopes() map[string]string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type OpenIDConnectSecurityScheme struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OpenIdConnectUrl string                 `protobuf:"bytes,1,opt,name=open_id_connect_url,json=openIdConnectUrl,proto3" json:"open_id_connect_url,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenIDConnectSecurityScheme) Reset() {
	*x = OpenIDConnectSecurityScheme{}
	mi := &file_registry_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenIDConnectSecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIDConnectSecurityScheme) ProtoMessage() {}

func (x *OpenIDConnectSecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIDConnectSecurityScheme.ProtoReflect.Descriptor instead.
func (*OpenIDConnectSecurityScheme) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{25}
}

func (x *OpenIDConnectSecurityScheme) GetOpenIdConnectUrl() string {
	if x != nil {
		return x.OpenIdConnectUrl
	}
	return ""
}

func (x *OpenIDConnectSecurityScheme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AgentCardSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *structpb.Struct       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Protected     string                 `protobuf:"bytes,2,opt,name=protected,proto3" json:"protected,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCardSignature) Reset() {
	*x = AgentCardSignature{}
	mi := &file_registry_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCardSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCardSignature) ProtoMessage() {}

func (x *AgentCardSignature) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCardSignature.ProtoReflect.Descriptor instead.
func (*AgentCardSignature) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{26}
}

func (x *AgentCardSignature) GetHeader() *structpb.Struct {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AgentCardSignature) GetProtected() string {
	if x != nil {
		return x.Protected
	}
	return ""
}

func (x *AgentCardSignature) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_registry_proto protoreflect.FileDescriptor

const file_registry_proto_rawDesc = "" +
	"\n" +
	"\x0eregistry.proto\x12\x0fa2a.registry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x9a\x01\n" +
	"\x14RegisterAgentRequest\x129\n" +
	"\n" +
	"agent_card\x18\x01 \x01(\v2\x1a.a2a.registry.v1.AgentCardR\tagentCard\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xb3\x01\n" +
	"\x12UpdateAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x129\n" +
	"\n" +
	"agent_card\x18\x02 \x01(\v2\x1a.a2a.registry.v1.AgentCardR\tagentCard\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"/\n" +
	"\x12DeleteAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x15\n" +
	"\x13DeleteAgentResponse\"\x87\x01\n" +
	"\x11ListAgentsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x14\n" +
	"\x05skill\x18\x04 \x01(\tR\x05skill\x12\x1a\n" +
	"\bverified\x18\x05 \x01(\bR\bverified\"\x90\x01\n" +
	"\x12ListAgentsResponse\x126\n" +
	"\x06agents\x18\x01 \x03(\v2\x1e.a2a.registry.v1.RegistryEntryR\x06agents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"-\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"q\n" +
	"\x11HeartbeatResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12A\n" +
	"\x0elast_heartbeat\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\"\xb3\x03\n" +
	"\rRegistryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x129\n" +
	"\n" +
	"agent_card\x18\x03 \x01(\v2\x1a.a2a.registry.v1.AgentCardR\tagentCard\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\x12?\n" +
	"\rregistered_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12=\n" +
	"\flast_updated\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12A\n" +
	"\x0elast_heartbeat\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xdd\a\n" +
	"\tAgentCard\x12\x10\n" +
	"\x03did\x18\x01 \x01(\tR\x03did\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12+\n" +
	"\x11documentation_url\x18\x04 \x01(\tR\x10documentationUrl\x12\x19\n" +
	"\bicon_url\x18\x05 \x01(\tR\aiconUrl\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12)\n" +
	"\x10protocol_version\x18\a \x01(\tR\x0fprotocolVersion\x12:\n" +
	"\bprovider\x18\b \x01(\v2\x1e.a2a.registry.v1.AgentProviderR\bprovider\x12R\n" +
	"\x14supported_interfaces\x18\t \x03(\v2\x1f.a2a.registry.v1.AgentInterfaceR\x13supportedInterfaces\x12F\n" +
	"\fcapabilities\x18\n" +
	" \x01(\v2\".a2a.registry.v1.AgentCapabilitiesR\fcapabilities\x123\n" +
	"\x06skills\x18\v \x03(\v2\x1b.a2a.registry.v1.AgentSkillR\x06skills\x12.\n" +
	"\x13default_input_modes\x18\f \x03(\tR\x11defaultInputModes\x120\n" +
	"\x14default_output_modes\x18\r \x03(\tR\x12defaultOutputModes\x125\n" +
	"\bsecurity\x18\x0e \x03(\v2\x19.a2a.registry.v1.SecurityR\bsecurity\x12Z\n" +
	"\x10security_schemes\x18\x0f \x03(\v2/.a2a.registry.v1.AgentCard.SecuritySchemesEntryR\x0fsecuritySchemes\x12C\n" +
	"\n" +
	"signatures\x18\x10 \x03(\v2#.a2a.registry.v1.AgentCardSignatureR\n" +
	"signatures\x12O\n" +
	"$supports_authenticated_extended_card\x18\x11 \x01(\bR!supportsAuthenticatedExtendedCard\x1ac\n" +
	"\x14SecuritySchemesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.a2a.registry.v1.SecuritySchemeR\x05value:\x028\x01\"E\n" +
	"\rAgentProvider\x12\"\n" +
	"\forganization\x18\x01 \x01(\tR\forganization\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"M\n" +
	"\x0eAgentInterface\x12)\n" +
	"\x10protocol_binding\x18\x01 \x01(\tR\x0fprotocolBinding\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xdb\x01\n" +
	"\x11AgentCapabilities\x12\x1c\n" +
	"\tstreaming\x18\x01 \x01(\bR\tstreaming\x12-\n" +
	"\x12push_notifications\x18\x02 \x01(\bR\x11pushNotifications\x128\n" +
	"\x18state_transition_history\x18\x03 \x01(\bR\x16stateTransitionHistory\x12?\n" +
	"\n" +
	"extensions\x18\x04 \x03(\v2\x1f.a2a.registry.v1.AgentExtensionR\n" +
	"extensions\"\x91\x01\n" +
	"\x0eAgentExtension\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12/\n" +
	"\x06params\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06params\"\xfd\x01\n" +
	"\n" +
	"AgentSkill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bexamples\x18\x04 \x03(\tR\bexamples\x12\x1f\n" +
	"\vinput_modes\x18\x05 \x03(\tR\n" +
	"inputModes\x12!\n" +
	"\foutput_modes\x18\x06 \x03(\tR\voutputModes\x125\n" +
	"\bsecurity\x18\a \x03(\v2\x19.a2a.registry.v1.SecurityR\bsecurity\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\"\xa5\x01\n" +
	"\bSecurity\x12@\n" +
	"\aschemes\x18\x01 \x03(\v2&.a2a.registry.v1.Security.SchemesEntryR\aschemes\x1aW\n" +
	"\fSchemesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.a2a.registry.v1.StringListR\x05value:\x028\x01\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x8b\x03\n" +
	"\x0eSecurityScheme\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12@\n" +
	"\aapi_key\x18\x02 \x01(\v2%.a2a.registry.v1.APIKeySecuritySchemeH\x00R\x06apiKey\x12F\n" +
	"\thttp_auth\x18\x03 \x01(\v2'.a2a.registry.v1.HTTPAuthSecuritySchemeH\x00R\bhttpAuth\x12>\n" +
	"\x04mtls\x18\x04 \x01(\v2(.a2a.registry.v1.MutualTLSSecuritySchemeH\x00R\x04mtls\x12?\n" +
	"\x06oauth2\x18\x05 \x01(\v2%.a2a.registry.v1.OAuth2SecuritySchemeH\x00R\x06oauth2\x12B\n" +
	"\x04oidc\x18\x06 \x01(\v2,.a2a.registry.v1.OpenIDConnectSecuritySchemeH\x00R\x04oidcB\b\n" +
	"\x06scheme\"h\n" +
	"\x14APIKeySecurityScheme\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"w\n" +
	"\x16HTTPAuthSecurityScheme\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12#\n" +
	"\rbearer_format\x18\x02 \x01(\tR\fbearerFormat\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\";\n" +
	"\x17MutualTLSSecurityScheme\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"\x9b\x01\n" +
	"\x14OAuth2SecurityScheme\x121\n" +
	"\x05flows\x18\x01 \x01(\v2\x1b.a2a.registry.v1.OAuthFlowsR\x05flows\x12.\n" +
	"\x13oauth2_metadata_url\x18\x02 \x01(\tR\x11oauth2MetadataUrl\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x92\x02\n" +
	"\n" +
	"OAuthFlows\x12I\n" +
	"\x12authorization_code\x18\x01 \x01(\v2\x1a.a2a.registry.v1.OAuthFlowR\x11authorizationCode\x12I\n" +
	"\x12client_credentials\x18\x02 \x01(\v2\x1a.a2a.registry.v1.OAuthFlowR\x11clientCredentials\x126\n" +
	"\bimplicit\x18\x03 \x01(\v2\x1a.a2a.registry.v1.OAuthFlowR\bimplicit\x126\n" +
	"\bpassword\x18\x04 \x01(\v2\x1a.a2a.registry.v1.OAuthFlowR\bpassword\"\xf1\x01\n" +
	"\tOAuthFlow\x12+\n" +
	"\x11authorization_url\x18\x01 \x01(\tR\x10authorizationUrl\x12\x1b\n" +
	"\ttoken_url\x18\x02 \x01(\tR\btokenUrl\x12\x1f\n" +
	"\vrefresh_url\x18\x03 \x01(\tR\n" +
	"refreshUrl\x12>\n" +
	"\x06scopes\x18\x04 \x03(\v2&.a2a.registry.v1.OAuthFlow.ScopesEntryR\x06scopes\x1a9\n" +
	"\vScopesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x1bOpenIDConnectSecurityScheme\x12-\n" +
	"\x13open_id_connect_url\x18\x01 \x01(\tR\x10openIdConnectUrl\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x81\x01\n" +
	"\x12AgentCardSignature\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06header\x12\x1c\n" +
	"\tprotected\x18\x02 \x01(\tR\tprotected\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature2\x90\x04\n" +
	"\x0fRegistryService\x12V\n" +
	"\rRegisterAgent\x12%.a2a.registry.v1.RegisterAgentRequest\x1a\x1e.a2a.registry.v1.RegistryEntry\x12L\n" +
	"\bGetAgent\x12 .a2a.registry.v1.GetAgentRequest\x1a\x1e.a2a.registry.v1.RegistryEntry\x12R\n" +
	"\vUpdateAgent\x12#.a2a.registry.v1.UpdateAgentRequest\x1a\x1e.a2a.registry.v1.RegistryEntry\x12X\n" +
	"\vDeleteAgent\x12#.a2a.registry.v1.DeleteAgentRequest\x1a$.a2a.registry.v1.DeleteAgentResponse\x12U\n" +
	"\n" +
	"ListAgents\x12\".a2a.registry.v1.ListAgentsRequest\x1a#.a2a.registry.v1.ListAgentsResponse\x12R\n" +
	"\tHeartbeat\x12!.a2a.registry.v1.HeartbeatRequest\x1a\".a2a.registry.v1.HeartbeatResponseBEZCgithub.com/ThisaraWeerakoon/Agent-Mesh/pkg/api/v1/registry;registryb\x06proto3"

var (
	file_registry_proto_rawDescOnce sync.Once
	file_registry_proto_rawDescData []byte
)

func file_registry_proto_rawDescGZIP() []byte {
	file_registry_proto_rawDescOnce.Do(func() {
		file_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)))
	})
	return file_registry_proto_rawDescData
}

var file_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_registry_proto_goTypes = []any{
	(*RegisterAgentRequest)(nil),        // 0: a2a.registry.v1.RegisterAgentRequest
	(*GetAgentRequest)(nil),             // 1: a2a.registry.v1.GetAgentRequest
	(*UpdateAgentRequest)(nil),          // 2: a2a.registry.v1.UpdateAgentRequest
	(*DeleteAgentRequest)(nil),          // 3: a2a.registry.v1.DeleteAgentRequest
	(*DeleteAgentResponse)(nil),         // 4: a2a.registry.v1.DeleteAgentResponse
	(*ListAgentsRequest)(nil),           // 5: a2a.registry.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),          // 6: a2a.registry.v1.ListAgentsResponse
	(*HeartbeatRequest)(nil),            // 7: a2a.registry.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 8: a2a.registry.v1.HeartbeatResponse
	(*RegistryEntry)(nil),               // 9: a2a.registry.v1.RegistryEntry
	(*AgentCard)(nil),                   // 10: a2a.registry.v1.AgentCard
	(*AgentProvider)(nil),               // 11: a2a.registry.v1.AgentProvider
	(*AgentInterface)(nil),              // 12: a2a.registry.v1.AgentInterface
	(*AgentCapabilities)(nil),           // 13: a2a.registry.v1.AgentCapabilities
	(*AgentExtension)(nil),              // 14: a2a.registry.v1.AgentExtension
	(*AgentSkill)(nil),                  // 15: a2a.registry.v1.AgentSkill
	(*Security)(nil),                    // 16: a2a.registry.v1.Security
	(*StringList)(nil),                  // 17: a2a.registry.v1.StringList
	(*SecurityScheme)(nil),              // 18: a2a.registry.v1.SecurityScheme
	(*APIKeySecurityScheme)(nil),        // 19: a2a.registry.v1.APIKeySecurityScheme
	(*HTTPAuthSecurityScheme)(nil),      // 20: a2a.registry.v1.HTTPAuthSecurityScheme
	(*MutualTLSSecurityScheme)(nil),     // 21: a2a.registry.v1.MutualTLSSecurityScheme
	(*OAuth2SecurityScheme)(nil),        // 22: a2a.registry.v1.OAuth2SecurityScheme
	(*OAuthFlows)(nil),                  // 23: a2a.registry.v1.OAuthFlows
	(*OAuthFlow)(nil),                   // 24: a2a.registry.v1.OAuthFlow
	(*OpenIDConnectSecurityScheme)(nil), // 25: a2a.registry.v1.OpenIDConnectSecurityScheme
	(*AgentCardSignature)(nil),          // 26: a2a.registry.v1.AgentCardSignature
	nil,                                 // 27: a2a.registry.v1.AgentCard.SecuritySchemesEntry
	nil,                                 // 28: a2a.registry.v1.Security.SchemesEntry
	nil,                                 // 29: a2a.registry.v1.OAuthFlow.ScopesEntry
	(*structpb.Struct)(nil),             // 30: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 31: google.protobuf.Timestamp
}
var file_registry_proto_depIdxs = []int32{
	10, // 0: a2a.registry.v1.RegisterAgentRequest.agent_card:type_name -> a2a.registry.v1.AgentCard
	30, // 1: a2a.registry.v1.RegisterAgentRequest.metadata:type_name -> google.protobuf.Struct
	10, // 2: a2a.registry.v1.UpdateAgentRequest.agent_card:type_name -> a2a.registry.v1.AgentCard
	30, // 3: a2a.registry.v1.UpdateAgentRequest.metadata:type_name -> google.protobuf.Struct
	9,  // 4: a2a.registry.v1.ListAgentsResponse.agents:type_name -> a2a.registry.v1.RegistryEntry
	31, // 5: a2a.registry.v1.HeartbeatResponse.last_heartbeat:type_name -> google.protobuf.Timestamp
	10, // 6: a2a.registry.v1.RegistryEntry.agent_card:type_name -> a2a.registry.v1.AgentCard
	31, // 7: a2a.registry.v1.RegistryEntry.registered_at:type_name -> google.protobuf.Timestamp
	31, // 8: a2a.registry.v1.RegistryEntry.last_updated:type_name -> google.protobuf.Timestamp
	31, // 9: a2a.registry.v1.RegistryEntry.last_heartbeat:type_name -> google.protobuf.Timestamp
	30, // 10: a2a.registry.v1.RegistryEntry.metadata:type_name -> google.protobuf.Struct
	11, // 11: a2a.registry.v1.AgentCard.provider:type_name -> a2a.registry.v1.AgentProvider
	12, // 12: a2a.registry.v1.AgentCard.supported_interfaces:type_name -> a2a.registry.v1.AgentInterface
	13, // 13: a2a.registry.v1.AgentCard.capabilities:type_name -> a2a.registry.v1.AgentCapabilities
	15, // 14: a2a.registry.v1.AgentCard.skills:type_name -> a2a.registry.v1.AgentSkill
	16, // 15: a2a.registry.v1.AgentCard.security:type_name -> a2a.registry.v1.Security
	27, // 16: a2a.registry.v1.AgentCard.security_schemes:type_name -> a2a.registry.v1.AgentCard.SecuritySchemesEntry
	26, // 17: a2a.registry.v1.AgentCard.signatures:type_name -> a2a.registry.v1.AgentCardSignature
	14, // 18: a2a.registry.v1.AgentCapabilities.extensions:type_name -> a2a.registry.v1.AgentExtension
	30, // 19: a2a.registry.v1.AgentExtension.params:type_name -> google.protobuf.Struct
	16, // 20: a2a.registry.v1.AgentSkill.security:type_name -> a2a.registry.v1.Security
	28, // 21: a2a.registry.v1.Security.schemes:type_name -> a2a.registry.v1.Security.SchemesEntry
	19, // 22: a2a.registry.v1.SecurityScheme.api_key:type_name -> a2a.registry.v1.APIKeySecurityScheme
	20, // 23: a2a.registry.v1.SecurityScheme.http_auth:type_name -> a2a.registry.v1.HTTPAuthSecurityScheme
	21, // 24: a2a.registry.v1.SecurityScheme.mtls:type_name -> a2a.registry.v1.MutualTLSSecurityScheme
	22, // 25: a2a.registry.v1.SecurityScheme.oauth2:type_name -> a2a.registry.v1.OAuth2SecurityScheme
	25, // 26: a2a.registry.v1.SecurityScheme.oidc:type_name -> a2a.registry.v1.OpenIDConnectSecurityScheme
	23, // 27: a2a.registry.v1.OAuth2SecurityScheme.flows:type_name -> a2a.registry.v1.OAuthFlows
	24, // 28: a2a.registry.v1.OAuthFlows.authorization_code:type_name -> a2a.registry.v1.OAuthFlow
	24, // 29: a2a.registry.v1.OAuthFlows.client_credentials:type_name -> a2a.registry.v1.OAuthFlow
	24, // 30: a2a.registry.v1.OAuthFlows.implicit:type_name -> a2a.registry.v1.OAuthFlow
	24, // 31: a2a.registry.v1.OAuthFlows.password:type_name -> a2a.registry.v1.OAuthFlow
	29, // 32: a2a.registry.v1.OAuthFlow.scopes:type_name -> a2a.registry.v1.OAuthFlow.ScopesEntry
	30, // 33: a2a.registry.v1.AgentCardSignature.header:type_name -> google.protobuf.Struct
	18, // 34: a2a.registry.v1.AgentCard.SecuritySchemesEntry.value:type_name -> a2a.registry.v1.SecurityScheme
	17, // 35: a2a.registry.v1.Security.SchemesEntry.value:type_name -> a2a.registry.v1.StringList
	0,  // 36: a2a.registry.v1.RegistryService.RegisterAgent:input_type -> a2a.registry.v1.RegisterAgentRequest
	1,  // 37: a2a.registry.v1.RegistryService.GetAgent:input_type -> a2a.registry.v1.GetAgentRequest
	2,  // 38: a2a.registry.v1.RegistryService.UpdateAgent:input_type -> a2a.registry.v1.UpdateAgentRequest
	3,  // 39: a2a.registry.v1.RegistryService.DeleteAgent:input_type -> a2a.registry.v1.DeleteAgentRequest
	5,  // 40: a2a.registry.v1.RegistryService.ListAgents:input_type -> a2a.registry.v1.ListAgentsRequest
	7,  // 41: a2a.registry.v1.RegistryService.Heartbeat:input_type -> a2a.registry.v1.HeartbeatRequest
	9,  // 42: a2a.registry.v1.RegistryService.RegisterAgent:output_type -> a2a.registry.v1.RegistryEntry
	9,  // 43: a2a.registry.v1.RegistryService.GetAgent:output_type -> a2a.registry.v1.RegistryEntry
	9,  // 44: a2a.registry.v1.RegistryService.UpdateAgent:output_type -> a2a.registry.v1.RegistryEntry
	4,  // 45: a2a.registry.v1.RegistryService.DeleteAgent:output_type -> a2a.registry.v1.DeleteAgentResponse
	6,  // 46: a2a.registry.v1.RegistryService.ListAgents:output_type -> a2a.registry.v1.ListAgentsResponse
	8,  // 47: a2a.registry.v1.RegistryService.Heartbeat:output_type -> a2a.registry.v1.HeartbeatResponse
	42, // [42:48] is the sub-list for method output_type
	36, // [36:42] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_registry_proto_init() }
func file_registry_proto_init() {
	if File_registry_proto != nil {
		return
	}
	file_registry_proto_msgTypes[18].OneofWrappers = []any{
		(*SecurityScheme_ApiKey)(nil),
		(*SecurityScheme_HttpAuth)(nil),
		(*SecurityScheme_Mtls)(nil),
		(*SecurityScheme_Oauth2)(nil),
		(*SecurityScheme_Oidc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_proto_goTypes,
		DependencyIndexes: file_registry_proto_depIdxs,
		MessageInfos:      file_registry_proto_msgTypes,
	}.Build()
	File_registry_proto = out.File
	file_registry_proto_goTypes = nil
	file_registry_proto_depIdxs = nil
}
