// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: mesh.proto

package mesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task_Status int32

const (
	Task_STATUS_UNSPECIFIED Task_Status = 0
	Task_SUBMITTED          Task_Status = 1
	Task_WORKING            Task_Status = 2
	Task_COMPLETED          Task_Status = 3
	Task_FAILED             Task_Status = 4
)

// Enum value maps for Task_Status.
var (
	Task_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "SUBMITTED",
		2: "WORKING",
		3: "COMPLETED",
		4: "FAILED",
	}
	Task_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"SUBMITTED":          1,
		"WORKING":            2,
		"COMPLETED":          3,
		"FAILED":             4,
	}
)

func (x Task_Status) Enum() *Task_Status {
	p := new(Task_Status)
	*p = x
	return p
}

func (x Task_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_proto_enumTypes[0].Descriptor()
}

func (Task_Status) Type() protoreflect.EnumType {
	return &file_mesh_proto_enumTypes[0]
}

func (x Task_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_Status.Descriptor instead.
func (Task_Status) EnumDescriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{3, 0}
}

// TaskSendRequest initiates a new task.
type TaskSendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Context ID for multi-turn conversations.
	ContextId string `protobuf:"bytes,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// Target Agent ID for routing.
	TargetAgentId string `protobuf:"bytes,2,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	// The initial message to start the task.
	Message       *Message `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSendRequest) Reset() {
	*x = TaskSendRequest{}
	mi := &file_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSendRequest) ProtoMessage() {}

func (x *TaskSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSendRequest.ProtoReflect.Descriptor instead.
func (*TaskSendRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *TaskSendRequest) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *TaskSendRequest) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *TaskSendRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// GetTaskRequest retrieves a task by ID.
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CancelTaskRequest cancels a task by ID.
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *CancelTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Task represents the central unit of work.
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        Task_Status            `protobuf:"varint,3,opt,name=status,proto3,enum=api.v1.mesh.Task_Status" json:"status,omitempty"`
	History       []*Message             `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	Artifacts     []*Artifact            `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Task) GetStatus() Task_Status {
	if x != nil {
		return x.Status
	}
	return Task_STATUS_UNSPECIFIED
}

func (x *Task) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Task) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

// Message represents a communication turn.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Parts         []*Part                `protobuf:"bytes,3,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

// Part represents the content of a message.
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Part_TextPart
	//	*Part_FilePart
	//	*Part_DataPart
	Content       isPart_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *Part) GetContent() isPart_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Part) GetTextPart() string {
	if x != nil {
		if x, ok := x.Content.(*Part_TextPart); ok {
			return x.TextPart
		}
	}
	return ""
}

func (x *Part) GetFilePart() *FilePart {
	if x != nil {
		if x, ok := x.Content.(*Part_FilePart); ok {
			return x.FilePart
		}
	}
	return nil
}

func (x *Part) GetDataPart() *structpb.Struct {
	if x != nil {
		if x, ok := x.Content.(*Part_DataPart); ok {
			return x.DataPart
		}
	}
	return nil
}

type isPart_Content interface {
	isPart_Content()
}

type Part_TextPart struct {
	TextPart string `protobuf:"bytes,1,opt,name=text_part,json=textPart,proto3,oneof"`
}

type Part_FilePart struct {
	FilePart *FilePart `protobuf:"bytes,2,opt,name=file_part,json=filePart,proto3,oneof"`
}

type Part_DataPart struct {
	DataPart *structpb.Struct `protobuf:"bytes,3,opt,name=data_part,json=dataPart,proto3,oneof"`
}

func (*Part_TextPart) isPart_Content() {}

func (*Part_FilePart) isPart_Content() {}

func (*Part_DataPart) isPart_Content() {}

// FilePart represents a file content, either inline or via URI.
type FilePart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*FilePart_InlineBytes
	//	*FilePart_Uri
	Data          isFilePart_Data `protobuf_oneof:"data"`
	MimeType      string          `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePart) Reset() {
	*x = FilePart{}
	mi := &file_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePart) ProtoMessage() {}

func (x *FilePart) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePart.ProtoReflect.Descriptor instead.
func (*FilePart) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *FilePart) GetData() isFilePart_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FilePart) GetInlineBytes() []byte {
	if x != nil {
		if x, ok := x.Data.(*FilePart_InlineBytes); ok {
			return x.InlineBytes
		}
	}
	return nil
}

func (x *FilePart) GetUri() string {
	if x != nil {
		if x, ok := x.Data.(*FilePart_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

func (x *FilePart) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type isFilePart_Data interface {
	isFilePart_Data()
}

type FilePart_InlineBytes struct {
	InlineBytes []byte `protobuf:"bytes,1,opt,name=inline_bytes,json=inlineBytes,proto3,oneof"`
}

type FilePart_Uri struct {
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3,oneof"`
}

func (*FilePart_InlineBytes) isFilePart_Data() {}

func (*FilePart_Uri) isFilePart_Data() {}

// Artifact represents the final output of a task.
type Artifact struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MimeType string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*Artifact_Bytes
	//	*Artifact_Uri
	Content       isArtifact_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Artifact) GetContent() isArtifact_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Artifact) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Content.(*Artifact_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *Artifact) GetUri() string {
	if x != nil {
		if x, ok := x.Content.(*Artifact_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

type isArtifact_Content interface {
	isArtifact_Content()
}

type Artifact_Bytes struct {
	Bytes []byte `protobuf:"bytes,4,opt,name=bytes,proto3,oneof"`
}

type Artifact_Uri struct {
	Uri string `protobuf:"bytes,5,opt,name=uri,proto3,oneof"`
}

func (*Artifact_Bytes) isArtifact_Content() {}

func (*Artifact_Uri) isArtifact_Content() {}

// StreamEvent wraps A2A event types for streaming.
type StreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamEvent_StatusUpdate
	//	*StreamEvent_ArtifactUpdate
	Event         isStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *StreamEvent) GetEvent() isStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamEvent) GetStatusUpdate() *TaskStatusUpdate {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_StatusUpdate); ok {
			return x.StatusUpdate
		}
	}
	return nil
}

func (x *StreamEvent) GetArtifactUpdate() *TaskArtifactUpdate {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ArtifactUpdate); ok {
			return x.ArtifactUpdate
		}
	}
	return nil
}

type isStreamEvent_Event interface {
	isStreamEvent_Event()
}

type StreamEvent_StatusUpdate struct {
	StatusUpdate *TaskStatusUpdate `protobuf:"bytes,1,opt,name=status_update,json=statusUpdate,proto3,oneof"`
}

type StreamEvent_ArtifactUpdate struct {
	ArtifactUpdate *TaskArtifactUpdate `protobuf:"bytes,2,opt,name=artifact_update,json=artifactUpdate,proto3,oneof"`
}

func (*StreamEvent_StatusUpdate) isStreamEvent_Event() {}

func (*StreamEvent_ArtifactUpdate) isStreamEvent_Event() {}

// TaskStatusUpdate represents a change in task status.
type TaskStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        Task_Status            `protobuf:"varint,2,opt,name=status,proto3,enum=api.v1.mesh.Task_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Optional status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdate) Reset() {
	*x = TaskStatusUpdate{}
	mi := &file_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdate) ProtoMessage() {}

func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *TaskStatusUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatusUpdate) GetStatus() Task_Status {
	if x != nil {
		return x.Status
	}
	return Task_STATUS_UNSPECIFIED
}

func (x *TaskStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TaskArtifactUpdate represents a new artifact generated by the task.
type TaskArtifactUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Artifact      *Artifact              `protobuf:"bytes,2,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskArtifactUpdate) Reset() {
	*x = TaskArtifactUpdate{}
	mi := &file_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskArtifactUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskArtifactUpdate) ProtoMessage() {}

func (x *TaskArtifactUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskArtifactUpdate.ProtoReflect.Descriptor instead.
func (*TaskArtifactUpdate) Descriptor() ([]byte, []int) {
	return file_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *TaskArtifactUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskArtifactUpdate) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

var File_mesh_proto protoreflect.FileDescriptor

const file_mesh_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mesh.proto\x12\vapi.v1.mesh\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x88\x01\n" +
	"\x0fTaskSendRequest\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\tR\tcontextId\x12&\n" +
	"\x0ftarget_agent_id\x18\x02 \x01(\tR\rtargetAgentId\x12.\n" +
	"\amessage\x18\x03 \x01(\v2\x14.api.v1.mesh.MessageR\amessage\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11CancelTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa5\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.api.v1.mesh.Task.StatusR\x06status\x12.\n" +
	"\ahistory\x18\x04 \x03(\v2\x14.api.v1.mesh.MessageR\ahistory\x123\n" +
	"\tartifacts\x18\x05 \x03(\v2\x15.api.v1.mesh.ArtifactR\tartifacts\"W\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSUBMITTED\x10\x01\x12\v\n" +
	"\aWORKING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\"\x81\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12'\n" +
	"\x05parts\x18\x03 \x03(\v2\x11.api.v1.mesh.PartR\x05parts\"\x9e\x01\n" +
	"\x04Part\x12\x1d\n" +
	"\ttext_part\x18\x01 \x01(\tH\x00R\btextPart\x124\n" +
	"\tfile_part\x18\x02 \x01(\v2\x15.api.v1.mesh.FilePartH\x00R\bfilePart\x126\n" +
	"\tdata_part\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\bdataPartB\t\n" +
	"\acontent\"h\n" +
	"\bFilePart\x12#\n" +
	"\finline_bytes\x18\x01 \x01(\fH\x00R\vinlineBytes\x12\x12\n" +
	"\x03uri\x18\x02 \x01(\tH\x00R\x03uri\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeTypeB\x06\n" +
	"\x04data\"\x82\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x16\n" +
	"\x05bytes\x18\x04 \x01(\fH\x00R\x05bytes\x12\x12\n" +
	"\x03uri\x18\x05 \x01(\tH\x00R\x03uriB\t\n" +
	"\acontent\"\xa8\x01\n" +
	"\vStreamEvent\x12D\n" +
	"\rstatus_update\x18\x01 \x01(\v2\x1d.api.v1.mesh.TaskStatusUpdateH\x00R\fstatusUpdate\x12J\n" +
	"\x0fartifact_update\x18\x02 \x01(\v2\x1f.api.v1.mesh.TaskArtifactUpdateH\x00R\x0eartifactUpdateB\a\n" +
	"\x05event\"w\n" +
	"\x10TaskStatusUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.api.v1.mesh.Task.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"`\n" +
	"\x12TaskArtifactUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x121\n" +
	"\bartifact\x18\x02 \x01(\v2\x15.api.v1.mesh.ArtifactR\bartifact2\x94\x02\n" +
	"\x0eA2AMeshService\x12;\n" +
	"\bSendTask\x12\x1c.api.v1.mesh.TaskSendRequest\x1a\x11.api.v1.mesh.Task\x12D\n" +
	"\n" +
	"StreamTask\x12\x18.api.v1.mesh.StreamEvent\x1a\x18.api.v1.mesh.StreamEvent(\x010\x01\x129\n" +
	"\aGetTask\x12\x1b.api.v1.mesh.GetTaskRequest\x1a\x11.api.v1.mesh.Task\x12D\n" +
	"\n" +
	"CancelTask\x12\x1e.api.v1.mesh.CancelTaskRequest\x1a\x16.google.protobuf.EmptyB8Z6github.com/ThisaraWeerakoon/Agent-Mesh/pkg/api/v1/meshb\x06proto3"

var (
	file_mesh_proto_rawDescOnce sync.Once
	file_mesh_proto_rawDescData []byte
)

func file_mesh_proto_rawDescGZIP() []byte {
	file_mesh_proto_rawDescOnce.Do(func() {
		file_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)))
	})
	return file_mesh_proto_rawDescData
}

var file_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mesh_proto_goTypes = []any{
	(Task_Status)(0),              // 0: api.v1.mesh.Task.Status
	(*TaskSendRequest)(nil),       // 1: api.v1.mesh.TaskSendRequest
	(*GetTaskRequest)(nil),        // 2: api.v1.mesh.GetTaskRequest
	(*CancelTaskRequest)(nil),     // 3: api.v1.mesh.CancelTaskRequest
	(*Task)(nil),                  // 4: api.v1.mesh.Task
	(*Message)(nil),               // 5: api.v1.mesh.Message
	(*Part)(nil),                  // 6: api.v1.mesh.Part
	(*FilePart)(nil),              // 7: api.v1.mesh.FilePart
	(*Artifact)(nil),              // 8: api.v1.mesh.Artifact
	(*StreamEvent)(nil),           // 9: api.v1.mesh.StreamEvent
	(*TaskStatusUpdate)(nil),      // 10: api.v1.mesh.TaskStatusUpdate
	(*TaskArtifactUpdate)(nil),    // 11: api.v1.mesh.TaskArtifactUpdate
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 13: google.protobuf.Struct
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_mesh_proto_depIdxs = []int32{
	5,  // 0: api.v1.mesh.TaskSendRequest.message:type_name -> api.v1.mesh.Message
	0,  // 1: api.v1.mesh.Task.status:type_name -> api.v1.mesh.Task.Status
	5,  // 2: api.v1.mesh.Task.history:type_name -> api.v1.mesh.Message
	8,  // 3: api.v1.mesh.Task.artifacts:type_name -> api.v1.mesh.Artifact
	12, // 4: api.v1.mesh.Message.created_at:type_name -> google.protobuf.Timestamp
	6,  // 5: api.v1.mesh.Message.parts:type_name -> api.v1.mesh.Part
	7,  // 6: api.v1.mesh.Part.file_part:type_name -> api.v1.mesh.FilePart
	13, // 7: api.v1.mesh.Part.data_part:type_name -> google.protobuf.Struct
	10, // 8: api.v1.mesh.StreamEvent.status_update:type_name -> api.v1.mesh.TaskStatusUpdate
	11, // 9: api.v1.mesh.StreamEvent.artifact_update:type_name -> api.v1.mesh.TaskArtifactUpdate
	0,  // 10: api.v1.mesh.TaskStatusUpdate.status:type_name -> api.v1.mesh.Task.Status
	8,  // 11: api.v1.mesh.TaskArtifactUpdate.artifact:type_name -> api.v1.mesh.Artifact
	1,  // 12: api.v1.mesh.A2AMeshService.SendTask:input_type -> api.v1.mesh.TaskSendRequest
	9,  // 13: api.v1.mesh.A2AMeshService.StreamTask:input_type -> api.v1.mesh.StreamEvent
	2,  // 14: api.v1.mesh.A2AMeshService.GetTask:input_type -> api.v1.mesh.GetTaskRequest
	3,  // 15: api.v1.mesh.A2AMeshService.CancelTask:input_type -> api.v1.mesh.CancelTaskRequest
	4,  // 16: api.v1.mesh.A2AMeshService.SendTask:output_type -> api.v1.mesh.Task
	9,  // 17: api.v1.mesh.A2AMeshService.StreamTask:output_type -> api.v1.mesh.StreamEvent
	4,  // 18: api.v1.mesh.A2AMeshService.GetTask:output_type -> api.v1.mesh.Task
	14, // 19: api.v1.mesh.A2AMeshService.CancelTask:output_type -> google.protobuf.Empty
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_mesh_proto_init() }
func file_mesh_proto_init() {
	if File_mesh_proto != nil {
		return
	}
	file_mesh_proto_msgTypes[5].OneofWrappers = []any{
		(*Part_TextPart)(nil),
		(*Part_FilePart)(nil),
		(*Part_DataPart)(nil),
	}
	file_mesh_proto_msgTypes[6].OneofWrappers = []any{
		(*FilePart_InlineBytes)(nil),
		(*FilePart_Uri)(nil),
	}
	file_mesh_proto_msgTypes[7].OneofWrappers = []any{
		(*Artifact_Bytes)(nil),
		(*Artifact_Uri)(nil),
	}
	file_mesh_proto_msgTypes[8].OneofWrappers = []any{
		(*StreamEvent_StatusUpdate)(nil),
		(*StreamEvent_ArtifactUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_proto_rawDesc), len(file_mesh_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mesh_proto_goTypes,
		DependencyIndexes: file_mesh_proto_depIdxs,
		EnumInfos:         file_mesh_proto_enumTypes,
		MessageInfos:      file_mesh_proto_msgTypes,
	}.Build()
	File_mesh_proto = out.File
	file_mesh_proto_goTypes = nil
	file_mesh_proto_depIdxs = nil
}
