// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: pkg/api/v1/mesh/mesh.proto

package mesh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	A2AMeshService_SendTask_FullMethodName   = "/api.v1.mesh.A2AMeshService/SendTask"
	A2AMeshService_StreamTask_FullMethodName = "/api.v1.mesh.A2AMeshService/StreamTask"
	A2AMeshService_GetTask_FullMethodName    = "/api.v1.mesh.A2AMeshService/GetTask"
	A2AMeshService_CancelTask_FullMethodName = "/api.v1.mesh.A2AMeshService/CancelTask"
)

// A2AMeshServiceClient is the client API for A2AMeshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A2AMeshService defines the Sidecar Mesh Protocol adhering to the Agent2Agent (A2A) Protocol Specification.
type A2AMeshServiceClient interface {
	// Synchronous start of a task.
	SendTask(ctx context.Context, in *TaskSendRequest, opts ...grpc.CallOption) (*Task, error)
	// Bidirectional streaming for real-time interaction.
	StreamTask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamEvent, StreamEvent], error)
	// Retrieve the current state of a task.
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// Cancel an ongoing task.
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type a2AMeshServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewA2AMeshServiceClient(cc grpc.ClientConnInterface) A2AMeshServiceClient {
	return &a2AMeshServiceClient{cc}
}

func (c *a2AMeshServiceClient) SendTask(ctx context.Context, in *TaskSendRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, A2AMeshService_SendTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AMeshServiceClient) StreamTask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamEvent, StreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &A2AMeshService_ServiceDesc.Streams[0], A2AMeshService_StreamTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEvent, StreamEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type A2AMeshService_StreamTaskClient = grpc.BidiStreamingClient[StreamEvent, StreamEvent]

func (c *a2AMeshServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, A2AMeshService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a2AMeshServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, A2AMeshService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// A2AMeshServiceServer is the server API for A2AMeshService service.
// All implementations must embed UnimplementedA2AMeshServiceServer
// for forward compatibility.
//
// A2AMeshService defines the Sidecar Mesh Protocol adhering to the Agent2Agent (A2A) Protocol Specification.
type A2AMeshServiceServer interface {
	// Synchronous start of a task.
	SendTask(context.Context, *TaskSendRequest) (*Task, error)
	// Bidirectional streaming for real-time interaction.
	StreamTask(grpc.BidiStreamingServer[StreamEvent, StreamEvent]) error
	// Retrieve the current state of a task.
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	// Cancel an ongoing task.
	CancelTask(context.Context, *CancelTaskRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedA2AMeshServiceServer()
}

// UnimplementedA2AMeshServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedA2AMeshServiceServer struct{}

func (UnimplementedA2AMeshServiceServer) SendTask(context.Context, *TaskSendRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method SendTask not implemented")
}
func (UnimplementedA2AMeshServiceServer) StreamTask(grpc.BidiStreamingServer[StreamEvent, StreamEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamTask not implemented")
}
func (UnimplementedA2AMeshServiceServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedA2AMeshServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedA2AMeshServiceServer) mustEmbedUnimplementedA2AMeshServiceServer() {}
func (UnimplementedA2AMeshServiceServer) testEmbeddedByValue()                        {}

// UnsafeA2AMeshServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to A2AMeshServiceServer will
// result in compilation errors.
type UnsafeA2AMeshServiceServer interface {
	mustEmbedUnimplementedA2AMeshServiceServer()
}

func RegisterA2AMeshServiceServer(s grpc.ServiceRegistrar, srv A2AMeshServiceServer) {
	// If the following call panics, it indicates UnimplementedA2AMeshServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&A2AMeshService_ServiceDesc, srv)
}

func _A2AMeshService_SendTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AMeshServiceServer).SendTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AMeshService_SendTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AMeshServiceServer).SendTask(ctx, req.(*TaskSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AMeshService_StreamTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(A2AMeshServiceServer).StreamTask(&grpc.GenericServerStream[StreamEvent, StreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type A2AMeshService_StreamTaskServer = grpc.BidiStreamingServer[StreamEvent, StreamEvent]

func _A2AMeshService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AMeshServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AMeshService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AMeshServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A2AMeshService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2AMeshServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: A2AMeshService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2AMeshServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// A2AMeshService_ServiceDesc is the grpc.ServiceDesc for A2AMeshService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var A2AMeshService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.mesh.A2AMeshService",
	HandlerType: (*A2AMeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTask",
			Handler:    _A2AMeshService_SendTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _A2AMeshService_GetTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _A2AMeshService_CancelTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTask",
			Handler:       _A2AMeshService_StreamTask_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/api/v1/mesh/mesh.proto",
}
